-- MySQL Script generated by MySQL Workbench
-- Wed Oct 15 17:27:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdalumnos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdalumnos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdalumnos` ;
USE `bdalumnos` ;

-- -----------------------------------------------------
-- Table `bdalumnos`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdalumnos`.`facultad` (
  `idfacultad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idfacultad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdalumnos`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdalumnos`.`carrera` (
  `idcarrera` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `facultad_idfacultad` INT NOT NULL,
  PRIMARY KEY (`idcarrera`, `facultad_idfacultad`),
  INDEX `fk_carrera_facultad_idx` (`facultad_idfacultad` ASC) VISIBLE,
  CONSTRAINT `fk_carrera_facultad`
    FOREIGN KEY (`facultad_idfacultad`)
    REFERENCES `bdalumnos`.`facultad` (`idfacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdalumnos`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdalumnos`.`alumno` (
  `idalumno` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `registro` INT NULL,
  `carrera_idcarrera` INT NOT NULL,
  `carrera_facultad_idfacultad` INT NOT NULL,
  PRIMARY KEY (`idalumno`),
  INDEX `fk_alumno_carrera1_idx` (`carrera_idcarrera` ASC, `carrera_facultad_idfacultad` ASC) VISIBLE,
  CONSTRAINT `fk_alumno_carrera1`
    FOREIGN KEY (`carrera_idcarrera` , `carrera_facultad_idfacultad`)
    REFERENCES `bdalumnos`.`carrera` (`idcarrera` , `facultad_idfacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdalumnos`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdalumnos`.`materia` (
  `idmateria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idmateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdalumnos`.`examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdalumnos`.`examen` (
  `alumno_idalumno` INT NOT NULL,
  `materia_idmateria` INT NOT NULL,
  `fecha` TIMESTAMP(6) NULL,
  `nota` INT NULL,
  PRIMARY KEY (`alumno_idalumno`, `materia_idmateria`),
  INDEX `fk_alumno_has_materia_materia1_idx` (`materia_idmateria` ASC) VISIBLE,
  INDEX `fk_alumno_has_materia_alumno1_idx` (`alumno_idalumno` ASC) VISIBLE,
  CONSTRAINT `fk_alumno_has_materia_alumno1`
    FOREIGN KEY (`alumno_idalumno`)
    REFERENCES `bdalumnos`.`alumno` (`idalumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_materia_materia1`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `bdalumnos`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
